### ISSUE TITLE
Enhancement: Disabling HMD Mode when not in VR Mode

### ISSUE THREAD

**Issue by jamesAbantech** [openleap/aframe-leap-hands#11]
While AFrame is primarily a VR framework, I find the declarative nature of AFrame in building Three.js scenes much more readable and maintainable.  For that reason, I suggest that this library does not assume the Leap Motion is being used as part of an HMD. 

I have, as an experiment, already created listeners for the scene that will change the transform to HMD when put in VR mode.  However, it may be more desirable to have the HMD mode to exist independent of the mode in which AFrame is operating. 

Either way, let me know if you think this is a feature worth considering.

**Comment by donmccurdy** [comment]
I like the idea of supporting non-VR use cases, that seems very reasonable. But I'd rather not autodetect when HMD mode should be enabled or disabled — this would make debugging harder, for one thing, since my Leap Motion is taped to my headset. 🙂

Let's add an option to the [leap-system.js](https://github.com/openleap/aframe-leap-hands/blob/master/src/leap-system.js) schema so that it can be disabled explicitly. Usage would be:

``` html
<a-scene leap="hmd: false">
  <a-entity leap-hand="hand: left"></a-entity>
  <a-entity leap-hand="hand: right"></a-entity>
</a-scene>
```

I hope to be able to do that late next week, or feel free to send a PR if you're interested and have time!

**Comment by james-h-stephens** [comment]
I have some code that adds it to the leap-system.js, but my experience with _WebPack_ is incredibly limited. I have just been testing it by altering the disto files directly. I would be happy to work on it directly if I can better understand how you are resolving your external references to 'leapjs' and 'circular-array',

In lieu of that, feel free to copy the relevant lines (28 - 69) from [here](https://github.com/james-h-stephens/aframe-leap-hands/blob/master/src/leap-system.js#L28).

Lines 28-38 cover augmentation of the transform plugin.

The [enableDesktopMode](https://github.com/james-h-stephens/aframe-leap-hands/blob/master/src/leap-system.js#L40) method disables HMD and sets the transform to an arbitrary position I found to work for me.

The [enableHMDMode](https://github.com/james-h-stephens/aframe-leap-hands/blob/master/src/leap-system.js#L47) method enables HMD and sets the transform to the position that you had originally used.

As for the setting for HMD, perhaps create 3 enumeration: _true_, _false_, and _toggle_.

In regards to the _toggle_ setting, the [setAutoToggleHMD](https://github.com/james-h-stephens/aframe-leap-hands/blob/master/src/leap-system.js#L54) method hooks up to the [EnterVR](https://aframe.io/docs/0.3.0/core/scene.html#events_enter_vr) and [ExitVR](https://aframe.io/docs/0.3.0/core/scene.html#events_exit_vr) events to automatically toggle the switch between desktop mode and HMD mode.

**Comment by donmccurdy** [comment]
There's no need to worry about WebPack really, PRs don't update dist files. My release script automatically updates `dist/*` when I increment the version number, which would be done on my end later.

In terms of testing code, simply:

``` shell
# Downloads leapjs, circular-array, and dev dependencies from NPM
npm install

# Starts a local development build/refresh server with Browserify and Budo
npm run dev

# (Optional) Build a dist script, which should not be committed
npm run dist
```

These scripts are defined [here](https://github.com/openleap/aframe-leap-hands/blob/master/package.json#L6-L12).

I had in mind something like this, as a starting point.

``` javascript
/**
 * Leap Motion system for A-Frame.
 */
module.exports = {
  schema: {
    hmd: {default: true}
  },

  init: function () {
    this.controller = Leap.loop()
      .setOptimizeHMD(this.data.hmd)
      .use('aframeSystem');
  },

  getFrame: function () {
    return this.controller.frame();
  }
};
```

Adding support for position/rotation/scale transforms seems like a good idea, as you've done, but let's get to that separately from this change, because assumptions like scale=.001 seem a bit subjective.
